version: "3.5"
services:
  php_fpm:
    build: .
    container_name: laravel_php_fpm
    working_dir: /usr/share/nginx/laravel
    volumes:
        - ./laravel:/usr/share/nginx/laravel
  nginx:
      image: nginx:1.15
      container_name: laravel_nginx
      working_dir: /usr/share/nginx/laravel
      ports:
          - "8000:80"
      volumes:
          - ./laravel:/usr/share/nginx/laravel
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
      image: mysql:5.7
      container_name: laravel_mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=laravel
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=laravel
        - MYSQL_PASSWORD=password  
